package nexus.io.agent.model.base;

import nexus.io.db.activerecord.Model;
import nexus.io.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLlmChatHistory<M extends BaseLlmChatHistory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setSessionId(java.lang.Long sessionId) {
		set("session_id", sessionId);
		return (M)this;
	}
	
	public java.lang.Long getSessionId() {
		return getLong("session_id");
	}
	
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}
	
	public M setRole(java.lang.String role) {
		set("role", role);
		return (M)this;
	}
	
	public java.lang.String getRole() {
		return getStr("role");
	}
	
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public M setCitations(java.lang.String citations) {
		set("citations", citations);
		return (M)this;
	}
	
	public java.lang.String getCitations() {
		return getStr("citations");
	}
	
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public M setImages(java.lang.String images) {
		set("images", images);
		return (M)this;
	}
	
	public java.lang.String getImages() {
		return getStr("images");
	}
	
	public M setMetadata(java.lang.String metadata) {
		set("metadata", metadata);
		return (M)this;
	}
	
	public java.lang.String getMetadata() {
		return getStr("metadata");
	}
	
	public M setArgs(java.lang.String args) {
		set("args", args);
		return (M)this;
	}
	
	public java.lang.String getArgs() {
		return getStr("args");
	}
	
	public M setCodeResult(java.lang.String codeResult) {
		set("code_result", codeResult);
		return (M)this;
	}
	
	public java.lang.String getCodeResult() {
		return getStr("code_result");
	}
	
	public M setHidden(java.lang.Boolean hidden) {
		set("hidden", hidden);
		return (M)this;
	}
	
	public java.lang.Boolean getHidden() {
		return getBoolean("hidden");
	}
	
	public M setLiked(java.lang.Boolean liked) {
		set("liked", liked);
		return (M)this;
	}
	
	public java.lang.Boolean getLiked() {
		return getBoolean("liked");
	}
	
	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

