package nexus.io.agent.model;

import nexus.io.db.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("llm_chat_completion", "id", LlmChatCompletion.class);
		arp.addMapping("llm_chat_history", "id", LlmChatHistory.class);
		arp.addMapping("llm_chat_session", "id", LlmChatSession.class);
		arp.addMapping("llm_user_asked_questions", "id", LlmUserAskedQuestions.class);
		arp.addMapping("llm_vector_embedding", "id", LlmVectorEmbedding.class);
	}
}


