package nexus.io.agent.model;

import nexus.io.agent.model.base.BaseLlmChatCompletion;

/**
 * Generated by java-db.
 */
public class LlmChatCompletion extends BaseLlmChatCompletion<LlmChatCompletion> {
  private static final long serialVersionUID = 1L;
	public static final LlmChatCompletion dao = new LlmChatCompletion().dao();
	/**
	 * 
	 */
  public static final String tableName = "llm_chat_completion";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.String 
  public static final String request = "request";
  //java.lang.String 
  public static final String response = "response";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

